services:
  sensor-frontend:
    image: sensor-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ADMIN_API_BASE_URL: ${ADMIN_API_BASE_URL:-http://103.211.202.145:8097}
        USER_API_BASE_URL: ${USER_API_BASE_URL:-http://103.211.202.145:8097}
        USER_ADMIN_API_BASE_URL: ${USER_ADMIN_API_BASE_URL:-http://103.211.202.145:8097}
        ENGINEER_API_BASE_URL: ${ENGINEER_API_BASE_URL:-http://195.250.21.120:8097}
        VENDOR_API_BASE_URL: ${VENDOR_API_BASE_URL:-http://195.250.21.120:8097}
    ports:
      - "${APP_PORT:-8096}:80"
